- name: Install nginx
  hosts: web
  become: yes
  tasks:
  - name: install nginx if RHEL
    ansible.builtin.dnf:
      name: nginx   
      state: installed
      when: ansible_os_family == "RedHat"