- name: print the values
  hosts: local
  connection: local
  vars:
    course: deveops aws
    duration: 20days
    tools: #list
     - java
     - connection
     - .net
    modules: #map
     ci: cd
     devops: jenkins
  tasks:
  - name: print the variables
    ansible.builtin.debug:
    msg: Hello everyone welcome to my  {{ course }} with the   {{ duration }} offering {{ tools }} and the {{ modules }}

     
