- name: sandeepinc
  hosts: local
  vars_files:
  - var.yaml
  tasks:
  - name: print the values
    ansible.builtin.debug:
      msg: we are having {{ DEVOPS }} course with the {{ DURATION}} Trainer is {{ TRAINER }}
     

